### PR TITLE
Fixed visibility of controls during exam. fixes #87

### LINKED ISSUE #87: Cannot se Controls in Simulator when I'm running an exam
When I'm running the exam, no controls are visible. I can reach them using Tab, but for some reason they're not visible:

image

### PR DESCRIPTION
**Pull request by StudiousDesign**
obviously there is a great deal of UI work required but this fixes the main issue of missing buttons.

### CODE REVIEW

**Comment by bolorundurowb** [comment]
@StudiousDesign a fix for #87 has already been added. Thanks for the work. I would close this.

**Comment by djdill** [comment]
The installers haven't be rebuild with this fix as far as I can tell as I can't click buttons on windows 10 too

**Comment by StudiousDesign** [comment]
@djdill This pull request was not accepted as somebody else had already submitted a fix for the issue.

**Comment by djdill** [comment]
Thanks, the 2.3 builds on SF still are missing this fix as they have only been built in 2019 July or so
Would be nice to have a installer with the buttons working
Thanks for the advice too

**Pull request closed without merging**
