### PR TITLE
Mark questions for review

### PR DESCRIPTION
**Pull request by StudiousDesign**
This is the first of two parts.  This pull request allows users to mark questions in tests with a review flag.

To achieve this it was necessary to;

- Ensure each question is uniquely identifiable (added a Guid property on each question)

- Support patching of older exam versions (added a patching solution)

- Increased the version number to 4 (due to the current version only being major in exam files)

**Methodology of implementation**
User loads an existing exam and the patching system will patch it so each question get's a unique Id, alternatively a new exam is created and so each question will have a new Id as this is now native functionality from v4.

During the exam a user can use the new review checkbox (top right) to mark a question for review;  this is persisted in the exam file itself for now (pro's and con's of it being stored here).

This is then shown as checked or unchecked the next time the exam is taken.  I wanted to get this first PR in and tested on older exam file formats to check the patching algorithm.  

Next part will include;

1.Take an exam using only questions that are marked for review.

### CODE REVIEW

**Review by jadedmia — COMMENTED** [review]
Would really like this functionality

**Comment by StudiousDesign** [comment]
> Would really like this functionality

Sadly the original project owner seems to be AFK as no commits for a minimum of 14 months...

**Comment by jadedmia** [comment]
Bummer.  Wish someone would resurrect it - I thought it had some great
potential.

**Comment by bolorundurowb** [comment]
Hey @StudiousDesign it seems you have some conflicts

**Pull request closed without merging**
